### ISSUE TITLE
Create a fibonacci sequence

### ISSUE THREAD

**Issue by eaglejs** [eaglejs/interviewQuestions#8]
Create a function that accepts one parameter, and creates a fibonacci sequence and returns the entire list.

**Comment by aaronraff** [comment]
Should the parameter indicate the starting number in the sequence?

**Comment by eaglejs** [comment]
The parameter should indicate the number that it should stop on. Example:

Parameter = 7

Function returns: [ 1, 1, 3, 5, 8, 13, 21]

**Comment by aaronraff** [comment]
Is this something that needs to be solved or is this only for perspective employees?

**Comment by eaglejs** [comment]
I am a developer for Unisys, I'm trying to create something that other developers can work on and answer the questions so I can recommend them for a position. The goal here really is, "Can a developer demonstrate how to use not only Git properly, but code as well." That's what I am trying to solve. However, if you would like to contribute to the questions, or even make adjustments to how it is implemented. I would be ok with that as well. :) Ask me to create an issue so you can make a pull request on it and I will do so. This is definitely experimental. I want to improve on this idea.

**Comment by eaglejs** [comment]
These are great questions and I appreciate that you are asking. :)
